### ISSUE TITLE
[BUG] (pds) repo is out-of-date

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#115]
**Which repo (e.g., tx-logging)?**
pds 

**What went wrong?**
The repo is badly out-of-date.

**What did you expect should happen?**
It should:
 1. point to all the correct sub-repos
 2. have a readme that helps with finding all the relevant document (including HLA, HLD,  developer's guide, contributor's guide, install guide, release guide, and clinical variable documentation #76), 
 3. be public

**Anything else (e.g., Operating systems, sotware versions)?**
Do 1. and 2. before 3.; this is a bit urgent now that we have stakeholders that may also be contributors.

**Comment by xu-hao** [comment]
close because this has become obsolete
