### ISSUE TITLE
[DELV] (D7) manuscript / developer guide

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#138]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable (e.g., D5)?**
deliverable 7

**Which repo (e.g., tx-logging)?**

**Short name**
manuscript / developer guide

**Description**
manuscript / developer guide for our architecture, vocabulary, APIs

**Related tickets**

**Steps to close this ticket**

**Comment by rajshruti18** [comment]
This is a duplicate. Please refer to issue #229 .
