### ISSUE TITLE
[DELV] (9.3) model for DOAC AE risk

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#146]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable?**
deliverable 9.3

**Which repo (e.g., tx-logging)?**

**Short name**
model for DOAC AE risk

**Description**
use yukon mapper to train a model for predicting DOAC AE risk

**Related tickets**

**Steps to close this ticket**

**Comment by krobasky** [comment]
obsolete #226
