### ISSUE TITLE
[DELV] (D9.4) DOAC dosing model plugin

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#147]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable?**
deliverable 9.4

**Which repo (e.g., tx-logging)?**

**Short name**
DOAC dosing model plugin

**Description**
implement the DOAC AE risk model as a plugin for DOAC dosing

**Related tickets**

**Steps to close this ticket**

**Comment by krobasky** [comment]
obsolete #226
