### ISSUE TITLE
[DELV] (D5.3) FHIR server over sim data

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#166]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable?**
deliverable 5.3

**Which repo (e.g., tx-logging)?**

**Short name**
FHIR server over sim data

**Description**
stand a FHIR server over the simulated data

**Related tickets**

**Steps to close this ticket**

1. translate the PCORnet data into FHIR JSONs (use CAMP-FHIR, if it makes your life easier)
2. ingest into mongodb in FHIR plugin
3. serve up the FHIR resources so a mapper can use it
talk to Hao! :)

**Comment by krobasky** [comment]
We don't have a realistic dataset, and I'm not sure when that will come available, so let's use this 10-patient dataset (Emily gave it a look over and said it looked ok for our use):
`/projects/txscience/krobasky/covid/10-null`
The features in these data have no correlations, so any classifier should be as good as random.

**Comment by hyi** [comment]
I believe this is done pending testing from @krobasky on 1000 simulated patient data.

**Comment by hyi** [comment]
The test was done during the cowork day this week. Closing.
