### ISSUE TITLE
Data Pre-Processing: Medication codes 

### ISSUE THREAD

**Issue by rajshruti18** [RENCI/pds#174]
For task# 1 and 2

You have a file with code\tclass, like:
```
1007530 Sodium
1007530 Salt solutions
1007530 Electrolyte solutions
1009216 Antihypertensive Agents
1009216 Platelet Aggregation Inhibitors
1009216 Platelet aggregation inhibitors excl. heparin
1010035 Anesthetics, Local
```

So one drug can belong to multiple classes, and
you have a file (`MedicationRequest.keep.code-display-system`) with code\tdisplay\tsystem, like:
```
100272  Lactobacillus bulgaricus        http://www.nlm.nih.gov/research/umls/rxnorm
1007530 Calcium Chloride / Magnesium Chloride / Potassium Chloride / Sodium Acetate / Sodium Chloride / sodium citrate  http://www.nlm.nih.gov/research/umls/rxnorm
1009216 Epoprostenol 1.5 MG Injection [Veletri] http://www.nlm.nih.gov/research/umls/rxnorm
1010035 Lidocaine Hydrochloride 10 MG/ML Injectable Solution [Xylocaine]        http://www.nlm.nih.gov/research/umls/rxnorm
1010673 Lidocaine Hydrochloride 20 MG/ML Injectable Solution [Xylocaine]        http://www.nlm.nih.gov/research/umls/rxnorm
1010739 Lidocaine Hydrochloride 20 MG/ML Mucous Membrane Topical Solution       http://www.nlm.nih.gov/research/umls/rxnorm
1010755 Epinephrine 0.01 MG/ML / Lidocaine Hydrochloride 10 MG/ML Injectable Solution [Xylocaine with Epinephrine]      http://www.nlm.nih.gov/research/umls/rxnorm
```

The 'system' column should always be rxnorm
You can see there's a lot of duplication - 10163 and 101739 can both map to 'Lidocain Hydrochloride'

So the job is to take that code\tclass file (called `MedicationRequest.keep.code-class`) and use the other file to create a map between meds that are similar, e.g.:
```
1010035  6387  Lidocain    Anesthetics, Local
1010673  6387  Lidocain    Anesthetics, Local
1010755  107602  Epinephrine  Anesthetics, Local 
```
where the second code (e.g., `6387`) is the parent code of the ingredient (e.g., Lidocain or Lidocain + epinephrine). You should be able toget that second code in an automated fashion from the rxnav api, but I'm not sure what would be the restful call.

Useful tool:
https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=6387

Use `scp sraj@ht3.renci.org:/projects/txscience/sraj/MedicationRequest.keep.code-class .` to copy files from hatteras to your local computer; google and download an scp program, or use one that comes with putty. Alternatively, use winftp for a graphical ui.

**Comment by rajshruti18** [comment]
@krobasky Where do I find 'MedicationRequest.keep' file that you mentioned above? These are the files that I found after untarring:

- MedicationRequest.keep.class
- MedicationRequest.keep.code-class
- MedicationRequest.keep.code-display-system

**Comment by krobasky** [comment]
For the record, you can use `MedicationRequest.keep.code-display-system`, which has 735 lines, the same number of lines in `MedicationRequest.keep`. The only difference is that `MedicationRequest.keep` includes only the `code` column.

**Comment by krobasky** [comment]
Instead of starting with those 2 given files, now you need to create a file (JSON formatted, per Raphael) that maps ALL rxnorm codes to their constituent ingredients.

**Comment by krobasky** [comment]
So for example, you might:
1. create a file (as above) with ALL the medication codes, not just a subset of rxnorm codes
2. combine them together with ALL the known classes AND INGREDIENTS
3. translate that csv into a format that Raphael can easily use for a tx-paralex spec
(but you could also combine 2 & 3)
