### ISSUE TITLE
[Feature] Redundancies in lab results 

### ISSUE THREAD

**Issue by ryanoconnor285** [RENCI/pds#175]
**What problem(s) do you aim to solve?** 
You have code\tdisplay\tsystem, like:
```
2019-8  2019-8: Carbon dioxide:PPres:Pt:BldA:Qn http://loinc.org
2021-4  2021-4: Carbon dioxide:PPres:Pt:BldV:Qn http://loinc.org
2028-9  2028-9: Carbon dioxide:SCnc:Pt:Ser/Plas:Qn      http://loinc.org
2039-6  Carcinoembryonic Ag:MCnc:Pt:Ser/Plas:Qn http://loinc.org
```
The 'system' column should always be http://loinc.org
I don't even know what these labs mean for the most part. I would love to have some kind of key to go by for expected values - you should be able to find that on loinc.org, I think.

The task is to look up each code on LOINC, e.g.,: https://loinc.org/2019-8/, get the "Part Description"
and get the units and 'normal' range and insert them into a file with format:
`<loinc-code>\t<part-number>\t<units-and-range>\t<part-description-name>`
...where <units-and-range> can be had from the loinc.org
 e.g.:
`2019-8    LP15150-3    mm[Hg]:[35,45]    Carbon dioxide`
...from https://loinc.org/2019-8/

The motivation:
If I had the map you are going to create and I had a LOINC code, I could then map multiple LOINCs to the same 'Part' code, and normalize the lab values using that normal range, which would allow me to reduce the number of variables in my analysis.

Bonus points if you map to HPO, but this is not a priority and can be saved for after the admin dashboard:
https://icd.codes/icd10cm/M050

https://github.com/TheJacksonLaboratory/loinc2hpoAnnotation/blob/master/Data/TSVSingleFile/annotations.tsv

```
2019-8	Qn	FHIR	N	HP:0500164	true	2018-04-18T18:45:26	HPO:nvasilevsky	NA	NA	0.1	true	NA
2019-8	Qn	FHIR	H	HP:0012416	false	2018-04-18T18:45:26	HPO:nvasilevsky	NA	NA	0.1	true	NA
2019-8	Qn	FHIR	L	HP:0012417	false	2018-04-18T18:45:26	HPO:nvasilevsky	NA	NA	0.1	true	NA
```

for the example:
`2019-8    LP15150-3    mm[Hg]:[35,45]    Carbon dioxide    `
the task is just to see that the range on LOINC ([35,45]) makes sense with the HPO flags on the github (N,H,L), and if not, annotate that with a flag, like 'HP-yes' to indicate it's sync'd. e.g.:
`2019-8 LP15150-3 mm[Hg]:[35,45] Carbon dioxide  HP-yes `

I'd do that in the mapper, but the curation task is the same as described above.

**What implementation(s) do you suggest?** 
Mapping

**Anything else?**

**Comment by krobasky** [comment]
There's now code to do this on yukon
