### ISSUE TITLE
[Feature] ICD-9 codes need to be mapped to ICD-10 codes

### ISSUE THREAD

**Issue by ryanoconnor285** [RENCI/pds#176]
**What problem(s) do you aim to solve?** 
Conditions are a bit different, you have only code\tsystem, like:
```
034.0   http://hl7.org/fhir/sid/icd-9-cm
038.0   http://hl7.org/fhir/sid/icd-9-cm
038.12  http://hl7.org/fhir/sid/icd-9-cm
M10.09  http://hl7.org/fhir/sid/icd-10-cm
M10.9   http://hl7.org/fhir/sid/icd-10-cm
M11.20  http://hl7.org/fhir/sid/icd-10-cm
```
the 'system' column can be icd-9-cm or icd-10-cm. the 10 ones are great because I can probably auto-generate the names, but the 9 ones are older and need to be mapped to a 10 code if possible
Also, the decimal point usually indicates a hierarchy, which we can use. (edited) 
so google '034.0 icd 9 to icd 10', you see J0300 is the equivalent. so maybe the output always has the ICD-10 code in the first column, and only add the ICD9 code if it was in the file, so you might have:
```
034.0    J020    Acute pharyngitis                 J00-J06    Acute upper respiratory infections
         M10.09  Idiopathic gout, multiple sites   M05-M14    Inflammatory polyarthropathies
```
In this example, we don't enter an ICD9 code for gout because that code (in the example) doesn't show up in the file.
(in fact, it does show up, but this is just an example
so the output map format would be:
`[<ICD9-Code-if-present>]\t<ICD10-Code>\t<ICD10-Description>\t<ICD-Section>\t<ICD-section-description>`
see https://icd.codes for ICD10 names

http:/id.who.int misses 669 codes 
Good tool for converting ICD9 to ICD10: https://www.icd10data.com/Convert

**What feature solves it and why?** 
mapping

**What implementation(s) do you suggest?** 

**Anything else?**

**Comment by krobasky** [comment]
We changed the output spec to look like this:
`ICD 9 Code (if present)\tICD 10 Code\t ICD 10 Description\t ICD Section\t ICD section description\tICD10 chapter`

**Comment by krobasky** [comment]
To clarify: There should  be no spaces between the code and the `\t`

**Comment by krobasky** [comment]
There must be an ICD10 code for EVERY LINE

That is, be sure to map every ICD9 to an ICD10. The reverse is not true: no need to map every ICD10 to an ICD9.

**Comment by krobasky** [comment]
I now have code for doing this on yukon.
