### ISSUE TITLE
[BUG] (pds-dashboard-admin) no way to update required patient variables 

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#188]
**Which repo (e.g., tx-logging)?**
pds-dashbaord-admin
**Expected Behavior**
admin should be able to reduce the number of required patient variables for a mapper. The reason is that there may be 2 mappers installed with overlapping patient variables, and a dashboard may wish to use both mappers, so the admin needs to break the tie in order to allow for chaining the mappers.
**Actual Behavior**
there are currently no methods for updating the required patient varibles
**Information**
render these like you would the selectors; update by POSTing the new requiredPatientVariables array to pdspi-config/config 
**Steps to reproduce the behavior**

**Comment by davidborland** [comment]
Done
