### ISSUE TITLE
[BUG] (all) create common data model for all APIs 

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#195]
**Which repo (e.g., tx-logging)?**
The info in [this silent brainstorm document](https://docs.google.com/document/d/12PtrIBaZR0fEwicaBTbNNWIIEoS9SMMr4jaGq6OjfK8/edit
) will be used to create a Visio document, and that document will be handed to Laura for filing; the figure pasted into HLD document.

**Information**
This isn't really a bug, but an unexpected task that needs to be addressed urgently.

@hyi and myself can use the document above to move forward, in the meantime, on her tickets in order to accelerate our progress.

**Comment by rajshruti18** [comment]
Done! Please find CDM here: https://docs.google.com/document/d/12PtrIBaZR0fEwicaBTbNNWIIEoS9SMMr4jaGq6OjfK8/edit?usp=sharing

**Comment by krobasky** [comment]
Can you just check that the CDM is consistent with the specs in github repo pds-cdm-specs?

**Comment by rajshruti18** [comment]
Done!
