### ISSUE TITLE
[BUG] (pdspi-mapper-example) update the source code based on new YAML

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#199]
**Which repo (e.g., tx-logging)?**
https://github.com/RENCI/pdspi-mapper-example

**Information**
This isn't really a bug, but an unexpected task that needs to be addressed urgently.

Update the code to handle the YAML changes made by #198

**Comment by hyi** [comment]
Has updated the code to comply with the new API yaml spec and made sure all tests have passed. Closing the issue.
