### ISSUE TITLE
[BUG] (pds-dashboard-research) use new pds api

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#204]
**Which repo (e.g., tx-logging)?**
https://github.com/RENCI/pds-dashboard-research

**Information**
This isn't really a bug, but an unexpected task that needs to be addressed urgently.

Update the code to handle the YAML changes made by #202

**Comment by krobasky** [comment]
I'm pretty confident the YAML for pds is done, including nice examples for use. Let me know if you have questions, Hong is still working on getting the code working.
https://github.com/RENCI/pds/blob/master/api/openapi/my_api.yaml

**Comment by davidborland** [comment]
Done
