### ISSUE TITLE
[BUG] (pds, config, mapper, guidance, dashboards) roll-out v2 API to pds

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#207]
**Which repo (e.g., tx-logging)?**
https://github.com/RENCI/pds-dashboard-research, pds, pdspi-config, pdspi-mapper, pdspi-guidance, and to a lesser extent, pds-dashboard-admin

**Information**
This isn't really a bug, but an unexpected task that needs to be addressed urgently.

Deploy code changes to pds.renci.org and test after all the following tickets are closed and automated testing has passed:
#195, #196, #197, #198, #199, #200, #201, #202, #203, #204, #206

IMPORTANTLY: 
1. Be sure that API documentation at the bottom of the dashboard points to pds.renci.org instead of stage-pds.renci.org
2. Coordinate via #pds to make sure the teamis ready for the change before doing the deployment.

**Comment by davidborland** [comment]
Done
