### ISSUE TITLE
[BUG] (pds-dashboard-epicpoc) use new pds api

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#208]
**Which repo (e.g., tx-logging)?**
https://github.com/RENCI/pds-dashboard-epicpoc

**Information**
This isn't really a bug, but an unexpected task that needs to be addressed urgently.

Update the code to handle the YAML changes made by #202, #210, test, and if all automated testing works, deploy to epic-pds.renci.org

**Comment by davidborland** [comment]
Implemented
