### ISSUE TITLE
[BUG] (pdspi-guidance-sars) update yaml and source code based on new CDM

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#210]
**Which repo (e.g., tx-logging)?**
https://github.com/RENCI/pdspi-guidance-sars

**Information**
This isn't really a bug, but an unexpected task that needs to be addressed urgently.

Consider re-using YAML created from #200 

Then update the source.

**Comment by krobasky** [comment]
Please reuse the yaml from the pds-cdm-specs repo. They are correct and complete and will  make your API consistent with the others.

**Comment by hyi** [comment]
Done. Closing.
