### ISSUE TITLE
[DELV] (D2) tx-parallex use case (simple, DOAC)

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#215]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable?**
D2
**Which repos (e.g., tx-logging)?**

**Short name**
tx-parallex use case (simple, DOAC)
**Description**
high-throughput, computational phenotype mapping demonstration
**Related tickets**

**Steps to close this ticket**
@hyi AT notes: clone pdspi-mapper-parallex-example repo and run the acceptance test; be sure the test generates the data as specified in Kimberly's slides

**Comment by xu-hao** [comment]
@hyi  and @changon  have written the test cases.
