### ISSUE TITLE
[DELV] (D3)  tx-parallex mapper

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#216]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable?**
D3
**Which repos (e.g., tx-logging)?**

**Short name**
tx-parallex mapper
**Description**
mapper plugin that can be deployed with the PDS ecosystem, thus allowing the work product above to also be deployed with existing pds research dashboards and FHIR/EHR integrations. Will need Yukon access.
**Related tickets**
#215 
**Steps to close this ticket**
@hyi AT notes: clone pdspi-mapper-parallex-example repo and run the acceptance test; be sure the test generates the data as specified in Kimberly's slides

**Comment by xu-hao** [comment]
- [ ] read list of fhir bundles if not list then just one
- [ ] load additional modules as model param
- [ ] load spec as model param

**Comment by krobasky** [comment]
not QUITE done yet...
#233 has to be finished first (to update the pds API to include pid lists and to deploy containers to pds.renci.org), and then #242 (to productize the CLI)

**Comment by krobasky** [comment]
We still need to demonstrate the performance improvement - which is not quite there yet because containers that run on http are timing out.

**Comment by krobasky** [comment]
We should be able to run this on the kinston covid19 data to see if it works.

**Comment by xu-hao** [comment]
this is done
