### ISSUE TITLE
[DELV] (D3.1) FHIR plugin

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#217]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable?**
D3.1
**Which repos (e.g., tx-logging)?**

**Short name**
FHIR plugin
**Description**

**Related tickets**
#216 
**Steps to close this ticket**
@krobasky AT notes: clone pdspi-mapper-parallex-example repo and run the acceptance test; be sure the test generates the data as specified in Kimberly's slides

**Comment by xu-hao** [comment]
discussed with @krobasky

modify the resource api endpoint to return a list of batch-response bundles, each bundle contains resources for each patient, Patient resource, other resources are searchset bundles.

add support batch and batch-response bundles
