### ISSUE TITLE
[DELV] (D4) brute-force data mapper code & Data

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#219]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable?**
D4
**Which repos (e.g., tx-logging)?**

**Short name**
brute-force data mapper code & Data
**Description**
computational phenotype mapping that is not necessarily high-throughput, or generalizable, but aimed specifically at converting cdwh DOAC data to a format usable for modelling. The end product will be comparable in format to Hao's end product, enabling orthogonal approaches for checking our outputs.
**Related tickets**
#214 
**Steps to close this ticket**
@krobasky AT notes: can you find the same results on the tx-parallex analysis as you did on the csv table from Kimberly (infection, anemia, proton pumps)

**Comment by changon** [comment]
Done - have a spec working to get collapsed data and time series data (1 csv per patient) on yukon
