### ISSUE TITLE
[DELV] (D1) tx-parallex (Acceptance Test)

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#227]
( [Project Plan](http://bit.ly/pdspplan) )
Which deliverable?
D1

Which repos (e.g., tx-logging)?

Short name
tx-parallex

Description
AT for tx-parallex error handling

Related tickets
#214 

Steps to close this ticket
@krobasky AT Notes - clone tx-parallex repo and run the acceptance test; be sure the test has monad coding for all error types

**Comment by xu-hao** [comment]
this is done
