### ISSUE TITLE
[DELV] (D8) research dashboard (v2)

### ISSUE THREAD

**Issue by LauraCapps** [RENCI/pds#228]
( [Project Plan](http://bit.ly/pdspplan) )
**Which deliverable?**
D8

**Which repos (e.g., tx-logging)?**

**Short name**
research dashboard (v2)

**Description**
add D3 mapper and D7 guidance to research dashboard

**Related tickets**
#226 #216  

**Steps to close this ticket**
AT - @krobasky

**Comment by davidborland** [comment]
Done
