### ISSUE TITLE
Create ICD code mapping JSON file(s) from 9 to 10 to 11

### ISSUE THREAD

**Issue by hyi** [RENCI/pds#234]
Need to create mapping JSON output conforming what Raphael needs for his modeling work.

**Comment by hyi** [comment]
@changon @krobasky I have completed the mapping and the resulting JSON files can be found on yukon under /mnt/data/hyi/pds-icd-mapping/data/output. There are three JSON files corresponding to icd 9 to 10 mapping (containing 14567 mapped icd codes), icd 9 to 11 mapping (containing 11030 mapped icd codes), and icd 10 to 11 mapping (containing 15937 mapped icd codes). The mapping dictionary is in a simple format of ```"icd code to be mapped": "mapped icd code"``` so you can load the mapping dictionary in and use the icd code to be mapped as the key, and retrieve the mapped value directly without need for any additional loopup. Let me know if this is sufficient for your work and if yes, we can close this issue.

**Comment by changon** [comment]
Maps look good. Closing this!
