### ISSUE TITLE
[BUG] (multiple) consistently use camelCase in API

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#237]
**Which repo (e.g., tx-logging)?**
pds, pdspi-guidance-example, pdspi-

**Expected Behavior**
All the API parameters should be using camelCase

**Actual Behavior**
we have some `_` here and there

**Information**

Please replace:
- settings_requested with settingsRequested 
- fhir_piid with fhirPiid
- mapper_piid with mapperPiid
- settings_used with settingsUsed
close this ticket when the above replacements have been made in the following repo's, dockerhub containers successfully build, Hong has been notified to deploy on stage-pds, and the updates test out ok.
- [x] pds (pds/guidance, pds/patientVariables)
- [x] guidance (pdspi-guidance-example/guidance)
- [x] pds-cdm-specs (as needed)
- [x] CDM
- [x] other guidance plugins
- [x] pdspi-guidance-example-sars
- [x] pds-server-mock

**Comment by krobasky** [comment]
added 'mock' server and sars plugin

**Comment by rajshruti18** [comment]
Changes deployed on stage-pds.renci.org.
