### ISSUE TITLE
[BUG] (tx-parallex) scheduler is suboptimal 

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#243]
**Which repo (e.g., tx-logging)?**
tx-parallex

**Expected Behavior**
cores should be used relatively equally even when some tasks are heavier

**Actual Behavior**
tasks are distributed at random, so one worker might be unlucky enough to get a lot of tasks, making the rest of the workers wait on it.

**Information**
Need to work-around or close this ticket in order to close #216 

**Steps to reproduce the behavior**
make a task with a 10s 'wait', run the spec and watch the cores with htop
(Hao may have a better way to reproduce)

**Comment by xu-hao** [comment]
also we can repro by measure the run time of n task using n threads

**Comment by xu-hao** [comment]
benchmark shows this works
