### ISSUE TITLE
User doesn't see critical errors thrown by plugins

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#79]
You want the dashboard to be fault tolerant, and so errors from the plugins should be handled gracefully and even corrected if possible by the front-end (logging the faults for  the admin to investigate).

However, critical errors in the plugins should not be masked; for example a 'status code' might propagate an error like "that dosing model is currently off-line. Please contact the system adminsitrator". In the clinical view, that kind of critical plug-in failure should cause a BPA to alert the clinician that there are no dosing supports in-place.

To close this ticket:
1. design a solution for how to communicate these kinds of failures
2. checkin and deploy the tested code (create a purposefully failing plugin to test against)
3. solicit feedback from the team for your design (demonstrable with the new, failing plugin)
4. close the ticket after receiving positive feedback

**Comment by ryanoconnor285** [comment]
This is currently being handled by David's research dashboard
