### ISSUE TITLE
'calculation' should return more informative description

### ISSUE THREAD

**Issue by ryanoconnor285** [RENCI/pds#82]
Currently the aggregator is returning this to the front end for the clinical feature variable for age.  
calculation: "birthDate"
certitude: 2
clinical_feature_variable: "LOINC:30525-0"
description: "Patient age is calculated from their birth date.  Age is required for dosing."
title: "age"
unit: "year"
value: 19
warning: "Dosing for pediatric patients...

the key calculation should look more like this:

calculation: "Current date '2019-11-08' minus patient's birthdate (FHIR resource 'Patient' field>'birthDate' = '2001-01-01') "

**Comment by xu-hao** [comment]
this id one
