### ISSUE TITLE
Create simulated data to test cdw-h mapper, dpi plugins

### ISSUE THREAD

**Issue by krobasky** [RENCI/pds#92]
related to #90, #91 

We need to create the simulated dataset, and very importantly, devise a method to prove that none of the data are 'real' or reidentifiable to an individual in the real dataset.

One idea might be to devise a statistic for measuring the distance each real patient is from it's nearest simulated neighbor, assert a reasonable minimum distance, and exclude all simulated patients that are closer than that minimum.

**Comment by xu-hao** [comment]
this is done via synthea
